# Mode
production: false

# Minimal log level
log_level: trace

# Backend url
backend_scheme: http         # Scheme
backend_base_url: localhost  # Base service url
backend_port: '5000'         # Backend port

# API urls
backend_contracts: contracts
backend_logs: log
backend_call_off_orders: call-off-orders
backend_requests: requests